apiVersion: apps/v1
kind: Statefulset
metadata:
  name: mysqldb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mamathapati/clientapp:dbimage
          ports:
            - containerPort: 3306
          VolumeMounts:
           - name : myvolume
             mountpaths: /var/lib/mysql 
 volumeClaimTemplates:
  - metadata:
      name: myvolume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

