apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
spec:
  serviceName: mysqldb
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      imagePullSecrets:
      - name: mysecret
      containers:
      - name: mysqldb
        image: mamathapati/clientapp:dbimage
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: myvolume
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: myvolume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi


